// Child First Program Fidelity Checklist — July 2025 (© Child First 2025)
// Transcribed from "Child First Program Fidelity Checklist - July 2025_unrestricted.docx"
// (see docs/sources/SOURCES.md)
// Scale: 0 = Not present; 1 = Early development or a little progress;
// 2 = In place or good progress; 3 = Excellent progress or accomplished.
// If not applicable to your site, write NA under Comments.

import type { FormTemplate, TemplateItem } from './types'

const scored = (id: string, label: string): TemplateItem => ({
  id,
  type: 'scored_comment',
  label,
})

const note = (id: string, label: string): TemplateItem => ({ id, type: 'note', label })

export const programFidelity2025: FormTemplate = {
  id: 'program_fidelity_2025',
  version: 'July 2025',
  instrument: 'Child First Program Fidelity Checklist',
  title: 'Program Fidelity Checklist (July 2025)',
  shortName: 'Program 2025',
  copyright: '© Child First 2025',
  whenCompleted:
    'A self-assessment completed by the Clinical Supervisor in collaboration with their Clinical Teams and reviewed by the Senior Leader at each affiliate site. Completed at 3 months post implementation, at 6 months, and then every 6 months thereafter. At least two program fidelity checklists must be fully completed within an Accreditation review period. An honest self-assessment reveals areas of strength and challenge; sites use it to inform a collaborative plan to enhance practice.',
  dualMarking: false,
  color: 'purple',
  icon: '📊',
  headerFields: [
    { id: 'affiliateSiteName', label: 'Name of Affiliate Site', type: 'text' },
    { id: 'dateCompleted', label: 'Date Completed', type: 'date' },
  ],
  sections: [
    {
      id: 's1_target_population',
      title: '1. Target Population',
      items: [
        note('tp_age_note', 'Age: Target population at entry into Child First services is:'),
        scored('tp_pregnant', 'Pregnant caregivers — applicable at specific sites'),
        scored('tp_children', 'Children birth through 5 years (up to 6th birthday)'),
        note('tp_symptoms_note', 'Symptoms & concerns: Children and their families are eligible for Child First when there are:'),
        scored('tp_child_concerns', "Concerns about the child's behavior, emotions, development, or learning and/or"),
        scored('tp_family_challenges', "Family challenges or events that place the child's development at risk, especially trauma"),
        scored('tp_financial', 'Financial need and legal status: Families are enrolled without regard for ability to pay, Medicaid eligibility, commercial insurance, or legal status.'),
        scored('tp_voluntary', 'Voluntary service: All services need written consent from the legal guardian and are voluntary.'),
      ],
    },
    {
      id: 's2_context',
      title: '2. Context of Intervention',
      items: [
        scored('coi_location', 'Location of visits: Each family is visited by the Child First Clinical Team, comprised of a Mental Health & Developmental Clinician and Care Coordinator (CC) together or individually, with 85% or more of visits provided in-home. Families may be seen in another community site if there are safety or other pressing issues, with discussion with the Clinical Supervisor. Telehealth visits are also permitted, but do not constitute "in person" sessions. Unless there are extenuating circumstances, services are not provided in office-based settings.'),
        note('coi_frequency_note', 'Visit frequency:'),
        scored('coi_assessment_phase', 'Assessment phase (first month): Visits are scheduled twice per week, and both Clinicians and Care Coordinators visit families together.'),
        scored('coi_intervention_phase', 'Intervention phase: Each family is visited on at least a weekly basis with a designated time for appointments. Visits may increase in frequency per week if there is high family need.'),
        scored('coi_staff_participation', 'Staff participation: The specific needs of the family dictate the pattern of Team visitation and/or independent work for or with the family by either Clinician or CC. The presence of a staff member at a visit is a clinical decision, which includes issues of safety.'),
        scored('coi_caseload', 'Caseload: Each Child First Team typically carries between 10 and 16 families, such that they are able to complete a minimum of 10-12 home visits per 40-hour work week, based on state-specific agreements. Caseload varies based on frequency/intensity of service, success of planned visits, and need for increased travel time for very rural areas.'),
        scored('coi_new_staff', 'New staff build their caseload over time, with a full caseload within 6 months at the latest.'),
        scored('coi_length', 'Length of visit: Visits last an average duration of 60-90 minutes but may be longer.'),
        scored('coi_duration', 'Duration of service: Families are served for an average of 6 to 12 months. Services may continue if there are significant challenges that cannot be met by another community agency, with approval of the program Clinical Supervisor at the Child First affiliate site. Services must begin before the child is 6 years of age, but may be continued after the 6th birthday, based on the needs of the child and family.'),
      ],
    },
    {
      id: 's3_staffing',
      title: '3. Staffing',
      items: [
        scored('st_composition', 'Composition of Child First Team: The Child First Clinical Team includes a Mental Health/Developmental Clinician (referred to as a "Child Development Clinician or Specialist" when working with families) and a Care Coordinator. Ratio of Clinician to CC must be 1:1 (unless an exception is made).'),
        note('st_expertise_note', 'Expertise of staff: (See complete job descriptions.)'),
        scored('st_essential', 'Essential capacity of all staff is the ability to take a reflective stance with regard to self, child, and caregivers; flexibility; empathy; and humility.'),
        scored('st_senior_leader', 'Senior Leader: Representative from Child First affiliate (Executive Director, Agency Clinical Director, Program Manager, etc.), responsible for overseeing model fidelity, hiring, and implementation of the Child First model. The Senior Leader is at least 10% FTE.'),
        scored('st_clinical_supervisor', "Clinical Supervisor: Master's level or Doctoral level, independently licensed mental health clinician, with extensive child development background, five years' therapeutic experience with children 0-5 years, knowledge of adult mental health disorders, and three years' experience providing reflective, clinical supervision. The Clinical Supervisor is 100% FTE. In some circumstances, Changent may approve an exception. 2 Teams: minimum .5 FTE; 3 Teams: minimum .75 FTE; 4-5 Teams: minimum 1.0 FTE; 6 or more Teams: additional clinical supervisors are needed."),
        scored('st_clinician', "Mental Health/Developmental Clinician: Master's level or higher, license-eligible, and/or independently licensed to provide mental health treatment with at least three years' experience (preferred) in early childhood mental health and development. Re: licensing: refer to funding source with deference to applicable state, licensing boards and contractual obligations."),
        scored('st_care_coordinator', "Care Coordinator: Bachelor's level or higher (preferred) who has at least three years' experience with young children and multi-challenged families (preferred). Knowledge and experience in community-based services and supports in service area highly valued."),
        scored('st_hiring', 'Hiring of staff: If potential staff do not meet requirements, consultation with Child First Changent staff is required.'),
        note('st_teams_note', 'Child First Clinical Teams:'),
        scored('st_partners', 'All Clinicians and CCs should have "regular partners" that consistently visit families with them. Clinicians and CC should not have multiple partners (unless there are extenuating circumstances).'),
        scored('st_ratio', 'The preferred ratio is one full-time Clinical Supervisor to four Child First teams. Two or three teams may be allowed with Changent approval.'),
        scored('st_case_planning', "Clinicians and CCs engage in regular case planning to prepare for home visits, determine responsibilities in alignment with the treatment plan, and coordinate attendance at home visits to best meet the needs of the family. Clinical Supervisors, Clinicians and CCs demonstrate respect for the unique contribution each team member offers to the family's care."),
        scored('st_multilingual', 'Multilingual/multicultural staff: Each Child First affiliate site must have a minimum of one Team with linguistic competence appropriate for the non-English speaking community that is served. All staff must display cultural humility and be culturally competent.'),
      ],
    },
    {
      id: 's4_referral',
      title: '4. Referral and Prioritization',
      items: [
        note('rp_source_note', 'Source of referrals:'),
        scored('rp_broad', 'Referrals should come from a broad range of community providers. All referring community providers should fully explain Child First services to parents/caregivers.'),
        scored('rp_outside_area', 'Referrals may be accepted from outside the designated geographic area when there is urgent need, with permission from Changent. Refer to funding source for any additional contractual considerations for referrals.'),
        scored('rp_consent', 'At least verbal consent (written preferred) from the legal guardian is required for a provider to make a referral to Child First. Child First staff will then call the family. No family is required to call or come to the provider agency as part of the referral process.'),
        scored('rp_direct', 'Parents/legal guardians can contact a Child First provider directly if they have concerns about their child.'),
        scored('rp_priority', 'Priority: The Child First Priority Checklist is an optional tool. Children and families with urgent issues, e.g., change in primary caregiver (removal to foster placement or reunification), imminent school expulsion, eviction from housing should receive priority.'),
        scored('rp_state_criteria', 'States may have other specific priority criteria.'),
        scored('rp_processing', 'Processing: A call & letter and/or email and/or other HIPAA compliant correspondence to the referring agency & family should be completed within 48 hrs.'),
        scored('rp_emergencies', 'Emergencies: Child First is not an emergency service. Emergencies should be referred to local emergency services based on affiliate and state protocols. Child First must collaborate with this provider to obtain services for the family.'),
        note('rp_waitlist_note', 'Waitlist:'),
        scored('rp_waitlist_min', 'A waitlist should be kept with a minimum of 2 (4 preferred) families per Team, so that if an existing family closes, a new family can be rapidly engaged to fill the available time.'),
        scored('rp_triage', 'If a child can be well served by another program, then they should be triaged to that service. Families may continue on the Child First waitlist if this is the optimal service for the child and family. Families should be periodically contacted to update their status.'),
      ],
    },
    {
      id: 's5_engagement',
      title: '5. Engagement',
      items: [
        note('en_efforts_note', 'Efforts to engage families in home-based intervention:'),
        scored('en_4week', 'Efforts to engage hard-to-reach families should continue over a 4-week period.'),
        scored('en_strategies', 'Strategies to engage families should be culturally sensitive and may include multiple phone calls, letters, electronic communication, contact with referrer, notes left at the door, meeting at a community site, e.g., early care and education, pediatric primary care, family center, park, restaurant, etc.'),
        scored('en_extended', 'If there has been caregiver contact and clear interest, the engagement period (prior to first visit) may be extended beyond 4 weeks.'),
        scored('en_cancelled', 'Cancelled appointments or "no shows": During intervention, persistent efforts should be continued until there has been no enrolled caregiver contact for 4 weeks or enrolled caregiver verbally indicates that they do not want services from Child First. Then, the file may be closed.'),
      ],
    },
    {
      id: 's6_first_visit',
      title: '6. First Visit',
      items: [
        scored('fv_consents', 'Consents: Consent for Child First services must be signed prior to beginning services. Consent must be maintained in the clinical record.'),
        scored('fv_hipaa', 'HIPAA and Releases of Information: Forms must be signed and maintained in the clinical record.'),
        scored('fv_insurance', 'Insurance: Permission to bill must be signed as per agency protocol.'),
      ],
    },
    {
      id: 's7_assessment',
      title: '7. Comprehensive Assessment',
      items: [
        note('ca_note', 'Comprehensive, child and family assessment:'),
        scored('ca_begins', 'Assessments begin on the first visit, as per Child First Assessment Protocol, unless there are extenuating circumstances.'),
        scored('ca_domains', 'A comprehensive assessment includes the strengths, needs, priorities, and culture of the child and all members of the family. Domains include — Child: development, education, social-emotional development and behavior, cognition, motor skills, important relationships, trauma, and health. Caregivers: early history, relationships, trauma, mental health, health, and concrete needs.'),
        note('ca_required_note', 'Required assessment measures:'),
        scored('ca_baseline', 'Baseline Assessments: Baseline assessments should be completed by 60 days, prior to completion of the comprehensive clinical formulation.'),
        scored('ca_6month', '6 Month Assessments: These assessments serve as a guide to the progress of the work with the family and inform the goals of the treatment plan.'),
        scored('ca_discharge', 'Discharge Assessments: These assessments should be conducted prior to and inform the discussion with the family about termination.'),
        scored('ca_database', 'All assessment measures need to be entered into the Assessment Scoring Database or Child First Comprehensive Clinical Record (CFCR) within one week of completion of assessment.'),
        scored('ca_essential', 'Essential assessment information: Additional assessment information needs to be collected from caregiver discussion, caregiver-child interaction and play observations, the health provider, early care and education report and observations, prior service providers, etc.'),
        scored('ca_formulation', 'Formulation: A comprehensive clinical formulation, which reflects an understanding of the underlying contributions to and meaning of the child and family challenges, must be developed, shared with the family, and revised so that there is clear consensus with the family as to goals and priorities for intervention. This must be completed by 60 days. The formulation informs the content of the intervention and treatment plan.'),
      ],
    },
    {
      id: 's8_plan_of_care',
      title: '8. Child & Family Plan of Care (Treatment Plan)',
      items: [
        scored('poc_timeframe', 'Timeframe: The initial formulation, diagnosis, and treatment plan must be written per regulatory requirements in each state, including Medicaid if applicable. A Child First comprehensive clinical formulation and treatment plan must be completed by 60 days. (See individual state contractual agreements.)'),
        scored('poc_collaborative', 'Collaborative process: The Clinician and CC, in partnership with the family, develop a well-coordinated, comprehensive, family-driven plan of treatment goals, supports, and services.'),
        note('poc_content_note', 'Content of Child and Family Plan of Care:'),
        scored('poc_reflects', 'Reflects the strengths, needs, priorities, and culture of the family.'),
        scored('poc_goals', 'Includes all current treatment goals and activities for the child (and their family).'),
        scored('poc_services', 'Includes services for all family members, as they relate to the treatment goals.'),
        scored('poc_signatures', 'Signatures: The Child and Family Plan of Care must be signed by the caregiver/guardian, Clinician, CC, and Clinical Supervisor.'),
        scored('poc_revision', "Ongoing revision and review: The Child First Clinical Team reviews and revises Plan of Care (treatment plan) regularly with caregivers as goals are met and new priorities and needs are identified. All treatment plans should have evidence of review when clinically appropriate and/or when necessary, per their agency's expectations."),
        note('poc_notes_note', 'Progress notes:'),
        scored('poc_notes_goals', 'All progress notes must relate directly to the goals of treatment.'),
        scored('poc_notes_signed', 'Notes must be dated and signed by the team member providing the service. Second signatures on a note may include a licensed practitioner (if required by site).'),
      ],
    },
    {
      id: 's9_parent_child',
      title: '9. Parent-Child Intervention',
      items: [
        scored('pci_dyadic', 'Dyadic psychotherapy: Focus of intervention is on the caregiver-child relationship and caregiver reflection and problem-solving as the basis for relationship change.'),
        scored('pci_fidelity_framework', 'All Clinical Teams must complete the Child First Fidelity Framework, maintain 2 Fidelity cases at all times, and review the Fidelity Framework in reflective, clinical supervision.'),
        scored('pci_video', 'All Clinical Teams are required to use video as part of the intervention, unless legal guardian/caregiver has not consented.'),
        scored('pci_guidance', "Parent guidance: Intervention includes attention to the child's developmental stage and individual differences through caregiver guidance."),
        scored('pci_executive', 'Executive functioning: Enhancement of both caregiver and child executive functioning capacity is a critical component of the intervention.'),
      ],
    },
    {
      id: 's10_ece',
      title: '10. Mental Health Consultation with Early Care and Education (ECE)',
      items: [
        scored('ece_assessment', 'Assessment: If a child is routinely cared for outside of the home, the CF Clinician must include ECE as part of the assessment and intervention process. It enables the Clinician to better understand how the child functions within different environments and with other adults and peers.'),
        scored('ece_discussion', "Discussion with child's early care provider or teacher: This is to further understand the child's behavior, to understand what strategies have been used in childcare or classroom, and to help the teacher or childcare provider understand the meaning of the child's behavior."),
        scored('ece_strategies', "Formulate strategies with child's early care provider or teacher: A plan is developed in collaboration with the teacher or childcare provider to address the child's behavior and promote optimal development. The Clinician helps with implementation of the strategies."),
        scored('ece_collaboration', 'Collaboration among teachers and caregivers/parents: The Clinician works to develop mutual understanding and support among teachers/childcare providers and caregivers.'),
      ],
    },
    {
      id: 's11_care_coordination',
      title: '11. Care Coordination',
      items: [
        scored('cc_comprehensive', 'Comprehensive family services: The Care Coordinator connects the child and all family members with community-based services and supports.'),
        scored('cc_stabilization', 'Family stabilization: During the early weeks of intervention, care coordination efforts need to be most intense, in order to stabilize the family. When the family is stabilized, relationship-based issues are more successfully addressed.'),
        scored('cc_executive', 'Building adult executive functioning: All planning with the family is a collaborative process with the Care Coordinator in which the caregiver develops goals for the family, prioritizes those goals, develops action steps or strategies to reach those goals, develops a process for self-monitoring whether the goals are accomplished, and revises the goals based on this review.'),
        scored('cc_relationship', 'Relationship building: Listening closely and following through on needed concrete support and services builds trust and an alliance between the family and the Child First Clinical Team.'),
        scored('cc_reflective', 'Reflective care coordination: The meaning of the services to the family and the barriers to access must be understood without judgment. This informs the process of effectively connecting to community-based services and supports.'),
        scored('cc_sniff', 'Service Needs Inventory for Families (SNIFF): This provides an ongoing record of services that the family needs and wants, services that the Clinical Team feels might benefit the family, when the family was referred to services, and when the family obtained the services. This is an active document which must be kept up to date with completion at intake (within 60 days of admission), at least quarterly thereafter, and at discharge.'),
      ],
    },
    {
      id: 's12_termination',
      title: '12. Termination / Discharge',
      items: [
        scored('td_collaborative', 'Collaborative process: This is best as a collaborative decision based on significant progress or completion of the goals developed in the Child and Family Plan of Care.'),
        scored('td_disengagement', "Family disengagement: After one month of no-contact with family, in spite of both phone calls and letters/other HIPAA compliant written communication (as per protocol), the family's file may be closed."),
        scored('td_data', 'Discharge data: All families must have discharge assessment data.'),
        scored('td_summaries', 'Discharge summaries: All children and families should have discharge summaries, which document initial presentation, progress through intervention, and plans moving forward.'),
      ],
    },
    {
      id: 's13_supervision',
      title: '13. Clinical and Reflective Supervision',
      items: [
        scored('crs_supervisor', 'Clinical Supervisor: The Clinical Supervisor provides all clinical, reflective supervision to staff. They must maintain an "open-door" policy in case of acute clinical needs. If necessary, temporary coverage plans may be created through consultation with Changent. These coverage plans must support teams in accordance with model fidelity.'),
        scored('crs_supervisor_supervision', 'The Clinical Supervisor must receive weekly individual, clinical supervision by a senior clinician in the agency implementing Child First (or outside consultation arrangements must be made).'),
        scored('crs_consultation', 'The Clinical Supervisor must participate in individual, clinical, reflective consultation with the Child First State/Regional Clinical Lead or another Child First Senior Clinical Consultant.'),
        scored('crs_individual', 'Individual, clinical, reflective supervision: 1 hour/week of individual clinical, reflective supervision is required for both Clinician and Care Coordinator.'),
        scored('crs_team', 'Clinical Team clinical, reflective supervision: 1 hour/week of Clinical Team is required.'),
        scored('crs_group', 'Group reflective and clinical case supervision: 1 ½ hours/week of group is required.'),
        scored('crs_administrative', 'Administrative supervision: A minimum of 1 hour/month of programmatic or administrative supervision in a group setting is required.'),
      ],
    },
    {
      id: 's14_training',
      title: '14. Training and Reflective Consultation',
      items: [
        note('tr_training_note', 'Training:'),
        scored('tr_supervisor_training', 'Clinical Supervisor Training: Participation in the next available Clinical Supervisor Training post date of hire'),
        scored('tr_learning_collaborative', 'Learning Collaborative: Participation in four, live-remote multi-day Learning Sessions over approximately 9 months. Participation in 90% of sessions is required of all staff (unless there are extenuating circumstances with prior approval).'),
        scored('tr_cpp', 'Child-Parent Psychotherapy (CPP): Participation of all Clinical Supervisors and Clinicians in three, in-person/remote, multi-day trauma-informed CPP sessions.'),
        scored('tr_cpp_calls', 'CPP: Participation in 18 months of biweekly supervision calls.'),
        scored('tr_distance', 'Distance Learning Curriculum: On-line training modules, videoconferencing, reading, and observations between in-person Learning Sessions, as required.'),
        scored('tr_conferences', 'Child First Conferences: Participation, as offered.'),
        scored('tr_launch', 'Program Launch Clinical and Reflective Site Consultation: Participation in clinical reflective consultation with State/Regional Clinical Lead during the early implementation period. On-site or by videoconferencing.'),
        scored('tr_site_group', 'Affiliate site group for 1 ½ hours, weekly for 6 months, then as needed to support implementation and fidelity to Child First practice.'),
        scored('tr_supervisor_consult', 'Affiliate site Clinical Supervisor for 1 hour, weekly for 6 months. Ongoing biweekly reflective consultation continues throughout implementation, unless otherwise determined in collaboration with the Changent State/Regional Clinical Lead.'),
        scored('tr_network', "Clinical Supervisors' Network Meetings: Participation in 75% of monthly meetings. May include: clinical reflective consultation, peer support, problem solving around management issues."),
      ],
    },
    {
      id: 's15_data',
      title: '15. Data Entry and Management',
      items: [
        scored('de_training', 'Data Training: Ensure staff complete all CFCR training prerequisites and participate in required CFCR trainings and CFCR Learning Sessions 1-4 via live-remote training.'),
        note('de_entry_note', 'Data entry:'),
        scored('de_5days', 'All data must be entered into the Child First Comprehensive Clinical Record (CFCR) & Assessment Scoring Database (ASD) per affiliate site standards or within 5 days, whichever is less.'),
        scored('de_timeframes', 'Assessment Measures are administered according to the timeframes in the Assessment Protocol.'),
        scored('de_supervisor', 'Clinical Supervisor ensures that affiliate site staff enter data timely, thoroughly, and accurately.'),
        scored('de_accounts', 'User Accounts: Clinical Supervisors maintain up to date user accounts, including creating user accounts for all new staff in certification and production; keeping credentials up to date; end dating employment histories and timely revocation of staff access to CFCR upon separation of employment.'),
        scored('de_communications', 'Responsive to Communications: Clinical Supervisors distribute communications received from the DQE Department via CFCR User Groups, CFCR Support Hub, emails and webinars, etc., and implement new processes and procedures as needed.'),
        scored('de_benchmarks', 'Benchmarks: All affiliate sites/programs must meet Benchmarks for Child First model fidelity.'),
        note('de_outcome_note', 'Outcome Analysis: (The Child First DQE conducts analysis of the assessment measure data and provides outcome reports to each affiliate on a quarterly basis.)'),
        scored('de_outcome_change', 'Clinical Supervisor reviews analysis of change from the baseline to discharge to determine whether expected improvement in child and family functioning is occurring.'),
        scored('de_outcome_teams', 'Clinical Supervisor reviews data from specific Clinical Teams to determine areas in need of further growth.'),
        scored('de_outcome_consultation', 'Clinical Supervisor identifies when there is a need for additional clinical consultation and training.'),
      ],
    },
    {
      id: 's16_cqe',
      title: '16. Continuous Quality Enhancement and Action Plans',
      items: [
        note('cqe_note', 'Continuous Quality Improvement:'),
        scored('cqe_leads', 'Clinical Supervisor leads quality enhancement at the site. The Clinical Supervisor uses data to understand their performance and the significance of their results; and create strategies to continuously improve Benchmarks and outcomes.'),
        scored('cqe_benchmarks', 'Each Child First affiliate program (Clinical Supervisor and Teams) reviews monthly Benchmark Reports and collaboratively problem solves and develops quality improvement strategies in areas in need of improvement.'),
        scored('cqe_summaries', 'Clinical Supervisors submit quarterly Quality Enhancement Summary forms to Changent, outlining reflection on their performance; areas for focused improvement; and short-term quality enhancement plans to address the identified areas for improvement.'),
        scored('cqe_network', "Strategies for improving implementation are shared at the Child First Clinical Supervisors' Network meeting."),
        scored('cqe_review', 'Clinical Supervisor reviews benchmarks and other performance markers (e.g., Accreditation components) with Child First State/Regional Clinical Lead on at least a quarterly basis.'),
        note('cqe_action_note', 'Action Plans:'),
        scored('cqe_action_specific', 'The Action Plans that the site creates identify specific actions, goals and timelines.'),
        scored('cqe_action_monitor', 'The Clinical Supervisor monitors and documents progress in meeting the goals of this plan on at least a biweekly basis.'),
        note('cqe_accreditation_note', 'Model Fidelity and Accreditation:'),
        scored('cqe_accreditation', 'All sites must participate in the Accreditation review, as outlined in the Child First Accreditation Guide, which includes, but is not limited to: Benchmarks and Assessment outcomes, clinical chart review, Clinical Fidelity Framework completion, training participation, Child First Infant and Early Childhood Community Collaborative documentation, and Self-Study.'),
        scored('cqe_levels', 'The Accreditation process results in four levels of program fidelity: Exemplary Fidelity, Consistent Fidelity, Inconsistent Fidelity, and Probation.'),
        scored('cqe_qep', 'Affiliate sites receiving Consistent Fidelity, Inconsistent Fidelity or Probation status must agree to participate in the development of a Quality Enhancement Plan and meet timelines in achieving service improvement in designated areas.'),
        scored('cqe_senior_leader', 'Any affiliate site receiving Inconsistent Fidelity or Probation status must have the site Senior Leader directly involved in the improvement strategies, with close monitoring of timelines and improvement in order to achieve agreed upon results.'),
      ],
    },
    {
      id: 's17_system_of_care',
      title: '17. Infant and Early Childhood System of Care',
      items: [
        scored('soc_collaboration', 'Infant and early childhood community collaboration: As part of Child First program fidelity, affiliate sites should demonstrate collaboration and community involvement through ongoing participation in an Infant and Early Childhood Community Collaborative. Affiliates have the freedom to determine the collaborative(s) they join based on the unique relationships within the region and must participate in at least one group that illustrates community partnerships and meet at least quarterly.'),
        note('soc_composition_note', 'Infant and early childhood community collaboratives or councils need to be composed of:'),
        scored('soc_parents', 'Parents and other primary caregivers'),
        scored('soc_child_welfare', 'Child welfare or protective services'),
        scored('soc_pediatric', 'Pediatric Primary Care and Dental — e.g., private providers, clinics, and/or hospitals'),
        scored('soc_ece', 'Early care and education — e.g., Head Start, School Readiness, childcare, kith and kin'),
        scored('soc_schools', 'Schools, local education association and/or Board of Education'),
        scored('soc_special_ed', 'Special education'),
        scored('soc_child_mh', 'Child mental health'),
        scored('soc_adult_mh', 'Adult mental health and substance abuse providers'),
        scored('soc_early_intervention', 'Early intervention (IDEA Part C)'),
        scored('soc_home_visiting', 'Home visiting models'),
        scored('soc_dv', 'Domestic violence agency/shelter'),
        scored('soc_housing', 'Homeless shelters and housing'),
        scored('soc_frc', 'Family resource and support centers'),
        scored('soc_courts', 'Courts'),
        scored('soc_dss', 'Department of Social Service'),
        scored('soc_health_dept', 'Health Department: WIC, Healthy Start'),
        scored('soc_obstetrics', 'Obstetrics'),
        scored('soc_faith', 'Faith-based organizations'),
        scored('soc_state', 'State agencies: MIECHV, Medicaid, Education, Disabilities'),
        scored('soc_special_health', 'Special health care needs'),
        scored('soc_other', 'Other — as per community need'),
      ],
    },
  ],
}
